title: Jekyll Theme - Fitness
email: cvetomir_vt@icloud.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my first fitness blog.
baseurl: "/jekyll-theme-fitness"
url: "" # the base hostname & protocol for your site, e.g. http://example.com
destination: "docs"

twitter_username: 
github_username:  MiroMutti

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed


exclude:
 - Gemfile
 - Gemfile.lock
 - node_modules
 - .gitignore
 - scss
 - gulpfile.js
 - package.json
 - package-lock.json
 - .vscode

